### ISSUE TITLE
其他语言编写

### ISSUE THREAD

**Issue by rc-power** [liuguangw/billing_go#1]
请问大神，这个billing能不能用java写出来？
顺便问一下客户端与Java服务端有没有可能通讯。。。。。

**Comment by liuguangw** [comment]
其他语言也是可以写出来的，用户登录时，会向服务端发送登录数据包，然后服务端处理后，再发送数数据包给billing。服务端与billing之间是使用TCP进行通讯的，所以你只要实现了这个TCP服务器的逻辑就可以了，与语言无关。
