### ISSUE TITLE
无法开启Server

### ISSUE THREAD

**Issue by rc-power** [liuguangw/billing_go#2]
./Server > /dev/null 2>&1
会出现这种错误

**Comment by liuguangw** [comment]
这是服务端的环境配置问题，与billing无关，billing即使挂掉了也不会影响到Server

**Comment by rc-power** [comment]
可我就改了个IP然后保存，就开不开了

**Comment by liuguangw** [comment]
那你要检查是哪里改错了

**Comment by rc-power** [comment]
`[System]
CurrentServerID=0
ServerNumber=2

EnableEffAudit=0
EffAuditSaveResultInterval=0
EffAuditReportInterval=0

EnableEffAuditSceneID_1ST=0
EnableEffAuditSceneID_2ND=0
EnableEffAuditSceneID_3RD=0
EnableEffAuditSceneID_3RD=0

[Mother]
IP=0.0.0.0
Port=0

[World]
IP=127.0.0.1
Port=777

[Billing]
Number=1
IP0=127.0.0.1
Port0=12680
IP1=0.0.0.0
Port1=10101
IP2=0.0.0.0
Port2=10101
IP3=0.0.0.0
Port3=10101
IP4=0.0.0.0
Port4=10101

[Proxy]
Proxy0ForCncUser= 0.0.0.0
;Proxy1ForCncUser=0.0.0.0
Proxy0ForCtcUser=0.0.0.0
;Proxy1ForCtcUser=0.0.0.0
Proxy0ForEduUser= 0.0.0.0
;Proxy1ForEduUser=0.0.0.0

[Server0]
ServerID=0
MachineID=0
IP0=192.168.200.132
Port0=3731
IP1=192.168.200.132
Port1=8880
Type=0
IP(CNC)= 0.0.0.0
Port(CNC)=1000
IP(CTC)=0.0.0.0
Port(CTC)=0
IP(EDU)= 0.0.0.0
Port(EDU)=1000
HumanSMKey=1001
PlayShopSMKey=4001
ItemSerialKey=7001
CommisionShopKey=6001
EnableShareMem=1

[Server1]
ServerID=2
MachineID=0
IP0=192.168.200.132
Port0=7384
IP1=192.168.200.132
Port1=8882
Type=1
IP(CNC)= 0.0.0.0
Port(CNC)=1000
IP(CTC)=0.0.0.0
Port(CTC)=0
IP(EDU)= 0.0.0.0
Port(EDU)=1000
HumanSMKey=1003
PlayShopSMKey=4003
ItemSerialKey=7003
CommisionShopKey=6003
EnableShareMem=0`

麻烦大神帮我看看

**Comment by liuguangw** [comment]
你自己分步启动查看是什么错误，如果这个文件只改了billing部分，应该是没有问题的

**Comment by rc-power** [comment]
我把server1和2的IP改了一下，分步启动Server时，只能启动到这
‘g_pGUIDManager->Init()...OK (-146974976)(T0=2019-7-8_16:0:49 T1=5.7310)
已杀死’
没说什么错误

**Comment by liuguangw** [comment]
你确定之前可以启动吗？如果没有任何错误提示，直接killed了，基本上就是内存不足导致的。

**Comment by rc-power** [comment]
额，还真是内存不足导致，我用的时centOS7 。
刚开始1G内存不行，后来换2G就可以呃！
谢谢
