### ISSUE TITLE
unknown billing data

### ISSUE THREAD

**Issue by rc-power** [liuguangw/billing_go#3]
偶然会查不到
unknown billing data
optype 0xc5
opdata。。。

还会断开连接

**Comment by rc-power** [comment]
只要登陆后过一会就会有这个问题：
‘[err][2019-07-13 13:49:46] unknown BillingData 
        OpType: 0xC5 
        OpData: [48 49 48 49 48 49 57 49 57 51 49 51 52 51 51 52 54 48 53 49 51 0 0 0 0 0 101 0 0 0 0 0 0 0 2 60 51 96 135 93 41 111 134 0 0 117 48 17 108 97 118 64 103 97 109 101 46 115 111 104 117 46 99 111 109 6 181 251 195 206 161 162 0 108 13 49 57 50 46 49 54 56 46 50 48 48 46 49 165 73 79 76 58 49 48 49 44 48 44 52 49 52 52 57 48 44 51 48 53 48 53 56 49 53 44 49 44 51 67 51 51 54 48 56 55 44 70 70 70 70 70 70 70 70 44 57 48 44 49 48 48 44 48 44 50 44 45 49 44 49 53 52 46 56 50 44 49 55 53 46 53 51 44 49 56 50 44 48 44 48 44 48 44 48 44 48 44 48 44 48 44 48 44 48 44 80 97 114 97 109 48 61 49 56 54 52 55 51 57 54 50 52 44 80 97 114 97 109 49 61 50 53 44 80 97 114 97 109 50 61 45 49 49 57 52 55 49 50 50 50 52 44 66 105 110 100 61 48 44 77 97 114 107 61 48 44 80 87 76 111 99 107 61 48]
[err][2019-07-13 13:49:46] client ip 192.168.200.100 disconnected,EOF
[log][2019-07-13 13:49:47] client ip 192.168.200.100 connected’

**Comment by rc-power** [comment]
现在发现 貌似是一买东西就会有上述情况

**Comment by rc-power** [comment]
GWLWGCostLogHandler::Execute ...Send to Billing OK key=010101919514193721035 (-305681600)(T0=2019-7-15_14:22:6 T1=3963.0640)
GWLWGCostLogHandler::Execute ...Send to Billing OK key=010101919514193750335 (-305681600)(T0=2019-7-15_14:22:6 T1=3963.2700)
GWLWGCostLogHandler::Execute ...Send to Billing OK key=010101919514193760635 (-305681600)(T0=2019-7-15_14:22:6 T1=3963.2700)
GWLWGCostLogHandler::Execute ...Send to Billing OK key=010101919514193771535 (-305681600)(T0=2019-7-15_14:22:6 T1=3963.2700)
GWLWGCostLogHandler::Execute ...Send to Billing OK key=010101919514193781636 (-305681600)(T0=2019-7-15_14:22:6 T1=3963.2700)
GWLWGCostLogHandler::Execute ...Send to Billing OK key=010101919514193792136 (-305681600)(T0=2019-7-15_14:22:6 T1=3963.2700)
GWLWGCostLogHandler::Execute ...Send to Billing OK key=010101919514193793236 (-305681600)(T0=2019-7-15_14:22:6 T1=3963.2700)
GWLWGCostLogHandler::Execute ...Send to Billing OK key=010101919514193702336 (-305681600)(T0=2019-7-15_14:22:6 T1=3963.4750)
GWLWGCostLogHandler::Execute ...Send to Billing OK key=010101919514193712336 (-305681600)(T0=2019-7-15_14:22:6 T1=3963.4750)
GWLWGCostLogHandler::Execute ...Send to Billing OK key=010101919514193824236 (-305681600)(T0=2019-7-15_14:22:6 T1=3963.4750)
GWLWGCostLogHandler::Execute ...Send to Billing OK key=010101919514193834536 (-305681600)(T0=2019-7-15_14:22:6 T1=3963.4750)
GWLWGCostLogHandler::Execute ...Send to Billing OK key=010101919514193864836 (-305681600)(T0=2019-7-15_14:22:6 T1=3963.4750)
貌似是这个的问题

**Comment by liuguangw** [comment]
0xC5的意义未知，所以也就没有处理这种类型的包，我分析过目前的有兑换功能的billing，都是不处理这种类型的数据包的，因为不知道如何处理
	
	
	0 1 0 1 0 1 9 1 9 3 1 3 4 3 3 4 6 0 5 1 3 � � � � � e � � � � � � �  < 3 ` ‡ ] ) o † � � u 
	0  l a v @ g a m e . s o h u . c o m  µ û Ã Î ¡ ¢ � l 
	1 9 2 . 1 6 8 . 2 0 0 . 1 ¥ I O L : 1 0 1 , 0 , 4 1 4 4 9 0 , 3 0 5 0 5 8 1 5 , 1 , 3 C 3 3 6 0 8 7 , 
	F F F F F F F F , 9 0 , 1 0 0 , 0 , 2 , - 1 , 1 5 4 . 8 2 , 1 7 5 . 5 3 , 1 8 2 , 
	0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 
	P a r a m 0 = 1 8 6 4 7 3 9 6 2 4 , P a r a m 1 = 2 5 , 
	P a r a m 2 = - 1 1 9 4 7 1 2 2 2 4 , 
	B i n d = 0 , M a r k = 0 , P W L o c k = 0

**Comment by rc-power** [comment]
每买一个东西就会发一个类似购买记录的数据，而且累计的久了，billing的响应会变得很慢，登陆，进游戏，查点数就会奇慢无比。

有时还会会出现billing断线重连的情况。

**Comment by liuguangw** [comment]
//数据包分析

	48 49 48 49 48 49 57 49 57 51 49 51 52 51 51 52 54 48 53 49 51 [00 ~ 20][21byte] ASCII:<01010 19193 13433 460513> (string)mSerial
	0 0 [21 ~ 22][2byte] 0 (ushort)zoneid
	0 0 0 101 [23 ~ 26][4byte] 101 (uint)mWorldId
	0 0 0 0 [27 ~ 30][4byte] 0 (uint)mServerId
	0 0 0 2 [31 ~ 33][4byte] 2 (uint)mSceneId
	60 51 96 135 [34 ~ 37][4byte] 1010000007 (uint)mUserGUID
	93 41 111 134 [38 ~ 41][4byte] 1562996614=2019/7/13 13:43:34 (uint)mCostTime
	0 0 117 48 [42 ~ 45][4byte] 30000 (uint)mYuanBao
	17 [46][1byte] 17 (byte)mAccLength
	108 97 118 64 103 97 109 101 46 115 111 104 117 46 99 111 109 [47 ~ 63][17byte] lav@game.sohu.com (string)mAccount
	6 [64][1byte] 6 (byte)mCharNameLength
	181 251 195 206 161 162 [65 ~ 70][6byte] <b5 fb c3 ce a1 a2>蝶梦、 (string)mCharName
	0 108 [71 ~ 72][2byte] 108 (ushort)mUserLevel
	13 [73][1byte] 13 (byte)mIPLength
	49 57 50 46 49 54 56 46 50 48 48 46 49 [74 ~ 86][13byte] 192.168.200.1 (string)mIP
	165 [89][1byte] 165 (byte)mOtherLength
	73 79 76 58 49 48 49 44 48 44 52 49 52 52 57 48 44 51 48 53 48 53 56 49 53 44 49 44 51 67 51 51 54 48 56 55 44 70 70 70 70 70 70 70 70 44 57 48 44 49 48 48 44 48 44 50 44 45 49 44 49 53 52 46 56 50 44 49 55 53 46 53 51 44 49 56 50 44 48 44 48 44 48 44 48 44 48 44 48 44 48 44 48 44 48 44 80 97 114 97 109 48 61 49 56 54 52 55 51 57 54 50 52 44 80 97 114 97 109 49 61 50 53 44 80 97 114 97 109 50 61 45 49 49 57 52 55 49 50 50 50 52 44 66 105 110 100 61 48 44 77 97 114 107 61 48 44 80 87 76 111 99 107 61 48
	[90 ~ 254][165byte] IOL:101,0,414490,30505815,1,3C336087,FFFFFFFF,90,100,0,2,-1,154.82,175.53,182,0,0,0,0,0,0,0,0,0,Param0=1864739624,Param1=25,Param2=-1194712224,Bind=0,Mark=0,PWLock=0 (string)mOtherLength

**Comment by rc-power** [comment]
额。。。
现在只要一买东西就会把billing给卡了，几乎没法登陆，查点。。。。。。必需重启billing

**Comment by liuguangw** [comment]
等周末了，我再详细的分析测试一下。。

**Comment by liuguangw** [comment]
我现在加上了`CostLogHandler`，你编译之后，替换原billing程序试试


//数据包分析如下

	48 49 48 49 48 49 57 49 57 51 49 51 52 51 51 52 54 48 53 49 51 [00 ~ 20][21byte] ASCII:<01010 19193 13433 460513> (string)mSerial
	0 0 [21 ~ 22][2byte] 0 (ushort)zoneid
	0 0 0 101 [23 ~ 26][4byte] 101 (uint)mWorldId
	0 0 0 0 [27 ~ 30][4byte] 0 (uint)mServerId
	0 0 0 2 [31 ~ 34][4byte] 2 (uint)mSceneId
	60 51 96 135 [35 ~ 38][4byte] 1010000007 (uint)mUserGUID
	93 41 111 134 [39 ~ 42][4byte] 1562996614=2019/7/13 13:43:34 (uint)mCostTime
	0 0 117 48 [43 ~ 46][4byte] 30000 (uint)mYuanBao
	17 [47][1byte] 17 (byte)mAccLength
	108 97 118 64 103 97 109 101 46 115 111 104 117 46 99 111 109 [48 ~ 64][17byte] lav@game.sohu.com (string)mAccount
	6 [65][1byte] 6 (byte)mCharNameLength
	181 251 195 206 161 162 [66 ~ 71][6byte] <b5 fb c3 ce a1 a2>蝶梦、 (string)mCharName
	0 108 [72 ~ 73][2byte] 108 (ushort)mUserLevel
	13 [74][1byte] 13 (byte)mIPLength
	49 57 50 46 49 54 56 46 50 48 48 46 49 [75 ~ 87][13byte] 192.168.200.1 (string)mIP
	165 [88][1byte] 165 (byte)mOtherLength
	73 79 76 58 49 48 49 44 48 44 52 49 52 52 57 48 44 51 48 53 48 53 56 49 53 44 49 44 51 67 51 51 54 48 56 55 44 70 70 70 70 70 70 70 70 44 57 48 44 49 48 48 44 48 44 50 44 45 49 44 49 53 52 46 56 50 44 49 55 53 46 53 51 44 49 56 50 44 48 44 48 44 48 44 48 44 48 44 48 44 48 44 48 44 48 44 80 97 114 97 109 48 61 49 56 54 52 55 51 57 54 50 52 44 80 97 114 97 109 49 61 50 53 44 80 97 114 97 109 50 61 45 49 49 57 52 55 49 50 50 50 52 44 66 105 110 100 61 48 44 77 97 114 107 61 48 44 80 87 76 111 99 107 61 48
	[89 ~ 254][165byte] IOL:101,0,414490,30505815,1,3C336087,FFFFFFFF,90,100,0,2,-1,154.82,175.53,182,0,0,0,0,0,0,0,0,0,Param0=1864739624,Param1=25,Param2=-1194712224,Bind=0,Mark=0,PWLock=0 (string)mOtherLength


	[aa 55 00 03 c5 77 77 55 aa]
	[aa 55 01 01 c5 77 77 ... 55 aa](257=0x 01 01)
	30 31 30 31 30 31 39 31 39 33 31 33 34 33 33 34 36 30 35 31 33 0 0 0 0 0 65 0 0 0 0 0 0 0 2 3c 33 60 87 5d 29 6f 86 0 0 75 30 11 6c 61 76 40 67 61 6d 65 2e 73 6f 68 75 2e 63 6f 6d 6 b5 fb c3 ce a1 a2 0 6c d 31 39 32 2e 31 36 38 2e 32 30 30 2e 31 a5 49 4f 4c 3a 31 30 31 2c 30 2c 34 31 34 34 39 30 2c 33 30 35 30 35 38 31 35 2c 31 2c 33 43 33 33 36 30 38 37 2c 46 46 46 46 46 46 46 46 2c 39 30 2c 31 30 30 2c 30 2c 32 2c 2d 31 2c 31 35 34 2e 38 32 2c 31 37 35 2e 35 33 2c 31 38 32 2c 30 2c 30 2c 30 2c 30 2c 30 2c 30 2c 30 2c 30 2c 30 2c 50 61 72 61 6d 30 3d 31 38 36 34 37 33 39 36 32 34 2c 50 61 72 61 6d 31 3d 32 35 2c 50 61 72 61 6d 32 3d 2d 31 31 39 34 37 31 32 32 32 34 2c 42 69 6e 64 3d 30 2c 4d 61 72 6b 3d 30 2c 50 57 4c 6f 63 6b 3d 30


	//short<opData 89bits>
	<30 31 30 31 30 31 39 31 39 33 31 33 34 33 33 34 36 30 35 31 33 00 00 00 00 00 65 00 00 00 00 00 00 00 02 3c 33 60 87 5d 29 6f 86 00 00 75 30 11 6c 61 76 40 67 61 6d 65 2e 73 6f 68 75 2e 63 6f 6d 06 b5 fb c3 ce a1 a2 00 6c 0d 31 39 32 2e 31 36 38 2e 32 30 30 2e 31 00>
	[aa 55 00 5c c5 77 77 ... 55 aa](92=0x5C)

	[aa 55 00 5c c5 77 77 30 31 30 31 30 31 39 31 39 33 31 33 34 33 33 34 36 30 35 31 33 00 00 00 00 00 65 00 00 00 00 00 00 00 02 3c 33 60 87 5d 29 6f 86 00 00 75 30 11 6c 61 76 40 67 61 6d 65 2e 73 6f 68 75 2e 63 6f 6d 06 b5 fb c3 ce a1 a2 00 6c 0d 31 39 32 2e 31 36 38 2e 32 30 30 2e 31 00 55 aa]


	Response
	[AA 55 00 19 C5 77 77 30 31 30 31 30 31 39 31 39 33 31 33 34 33 33 34 36 30 35 31 33 01 55 AA ]


	00 19 = 25
	C5 type
	77 77  ID
	30 31 30 31 30 31 39 31 39 33 31 33 34 33 33 34 36 30 35 31 33
	01

**Comment by rc-power** [comment]
还是会报unknown BillingData
GWLWGCostLogHandler::Execute ...Send to Billing OK key=010101919719320721510 (-305718464)(T0=2019-7-17_19:33:57 T1=235.2610)
GWLWGCostLogHandler::Execute ...Send to Billing OK key=010101919719320853210 (-305718464)(T0=2019-7-17_19:33:57 T1=235.2610)
GWLWGCostLogHandler::Execute ...Send to Billing OK key=010101919719320863610 (-305718464)(T0=2019-7-17_19:33:57 T1=235.2610)
GWLWGCostLogHandler::Execute ...Send to Billing OK key=010101919719320873810 (-305718464)(T0=2019-7-17_19:33:57 T1=235.2610)
[err][2019-07-17 19:34:33] unknown BillingData 
        OpType: 0xC5 
        OpData: [48 49 48 49 48 49 57 49 57 55 49 57 51 50 48 57 56 55 52 49 49 0 0 0 0 0 101 0 0 0 0 0 0 0 2 60 51 96 136 93 47 7 57 0 0 0 1 19 108 97 118 50 53 64 103 97 109 101 46 115 111 104 117 46 99 111 109 2 220 178 0 119 13 49 57 50 46 49 54 56 46 50 48 48 46 49 165 73 79 76 58 49 48 49 44 48 44 56 48 55 55 53 49 44 51 48 48 48 56 48 50 57 44 49 44 51 67 51 51 54 48 56 56 44 70 70 70 70 70 70 70 70 44 57 48 44 49 48 48 44 50 44 50 44 45 49 44 49 54 48 46 49 57 44 49 52 55 46 57 49 44 49 56 48 44 48 44 48 44 48 44 48 44 48 44 48 44 48 44 48 44 48 44 80 97 114 97 109 48 61 49 56 55 51 57 52 49 52 49 54 44 80 97 114 97 109 49 61 50 53 44 80 97 114 97 109 50 61 45 49 53 48 50 54 56 52 50 50 52 44 66 105 110 100 61 48 44 77 97 114 107 61 48 44 80 87 76 111 99 107 61 48]

**Comment by liuguangw** [comment]
你这明显没有编译啊，还用老版本测试结果不是一样的么，

**Comment by rc-power** [comment]
现在不会提示unknown BillingData，但还是退出登陆还是会卡验证密码，不知道是不是login卡了。。。
GWLWGCostLogHandler::Execute()...CostLog Save to Login OK! key=010101919721113688725 (-138774784)(T0=2019-7-17_21:12:48 T1=652.7520)
GWLWGCostLogHandler::Execute()...CostLog Save to Login OK! key=010101919721113600425 (-138774784)(T0=2019-7-17_21:12:48 T1=652.7520)
GWLWGCostLogHandler::Execute()...CostLog Save to Login OK! key=010101919721113630025 (-138774784)(T0=2019-7-17_21:12:49 T1=652.9580)
GWLWGCostLogHandler::Execute()...CostLog Save to Login OK! key=010101919721113771026 (-138774784)(T0=2019-7-17_21:12:49 T1=652.9580)

只要不买东西就没事，一买就卡

**Comment by liuguangw** [comment]
嗯，我已经发现原因了，过快的购买，导致了数据包的沉积，我刚刚提交了一个commit，可以解决这个问题了

**Comment by liuguangw** [comment]
之前的算法是每次从TCP读取到数据后，尝试解析billing包，如果解析到一个billing包，就处理，然后进入下一次的TCP数据读取。如果发现billing包还不完整，则缓存此数据，进入下一次读取，直到成功读取到一个完整的billing包，再处理billing包。

然而，假如两个billing包粘在一起，按照以前的逻辑，解析到一个billing包并处理之后，粘在后面的billing包并不会马上被处理，而是下次从TCP读取到数据之后，才会处理。所以粘包就会表现为反应很慢。


现在的做法是，从TCP读取到数据之后，无限循环解析billing包(之前只解析到一个包)，直到不能解析到一个完整的billing包为止，然后再从TCP进行读取。
